### ISSUE TITLE
enroll-casia1.py

### ISSUE THREAD

**Issue by graterol** [AntiAegis/Iris-Recognition#6]
hello, when i run python3 enroll-casia1.py does not enlist anyone, it throws me that the number of files enrolled is 0, and when i run python3 enroll-single.py it says "unrecognized arguments".. what could be the error? thanks.

**Comment by RobertoMaurizzi** [comment]
you need to specify parameters to the enroll commands, like 
`python enroll-casia1.py --temp_dir=templates/mixtest --data_dir=../CASIA1/*`

To verify an image it should be something like 
`python verify.py --temp_dir=templates/mixtest/ --file=yourfile.png`
but I can't test it right now because brew probably broke my opencv installation (cv2.imread returns None whatever I pass to it... 🤔 )

**Comment by graterol** [comment]
Thank you very much for answering, it worked 👍

**Comment by mahsa6310027328** [comment]
i need the segmentation part in python but i dont know which part must be run at first?please help me

**Comment by AntiAegis** [comment]
@mahsa6310027328, functions for the segmentation stage are in this script: https://github.com/AntiAegis/Iris-Recognition/blob/master/python/fnc/segment.py

**Comment by mahsa6310027328** [comment]
thanks a lot for your responding...but i cant finde in which part of code you give the address or direction of iris image folder?may you help me?

    On Monday, January 28, 2019, 5:00:58 AM GMT+3:30, Thuy Ng <notifications@github.com> wrote:  
 
 
Closed #6.

**Comment by AntiAegis** [comment]
@mahsa6310027328 
https://github.com/AntiAegis/Iris-Recognition/blob/master/python/enroll-casia1.py#L19
